version: '3.8'

services:

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:?err}
    environment:
      DEPLOYMENT_STAGE: 'STAGING'
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static-serve
      - media_volume:/backend/media-serve
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:${POSTGRES_VERSION:?err}-alpine
    user: ${DB_USERNAME:?err}
    environment:
      POSTGRES_DB: ${DB_NAME:?err}
      POSTGRES_USER: ${DB_USERNAME:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      POSTGRES_PORT: 5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    build:
      context: ./nginx/https
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:?err}
        DOMAIN_NAME: ${DOMAIN_NAME:?err}
    volumes:
      - static_volume:/static-serve
      - media_volume:/media-serve
      - ./nginx/https/vue_build:/vue_build
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    env_file:
      - ./.env
    depends_on:
      - django
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    pull_policy: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume:
  postgres_data:
